openapi: 3.0.0
info:
  title: Devices
  version: '1.0'
  description: |-
    Interact with the `'Devices Service'` API to get a list of registered devices, add or remove devices and updating existing records.

    Use this API to leverage __*CloudHome*__'s central repository of devices that will then allow users to manage home automation systems.

    ```javascript
    var s = "JavaScript syntax highlighting";
    alert(s);
    ```
  contact:
    name: Stephen Price
    url: 'https://www.linkedin.com/in/slprice/'
    email: stephen@stoplight.io
  termsOfService: cloudhome.io/api/devices/terms
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://cloudhome.io'
    description: CloudHome device platform
paths:
  '/api/devices/{accountid}/{spaceid}':
    get:
      summary: getDevices
      tags:
        - devices
        - IOT
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/devices.v1.json
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'https://apiguild.stoplight.io/api/v1/projects/apiguild/enterprise-schemas/nodes/error.v1.yaml?branch=master&deref=bundle'
      operationId: get-api-devices
      description: |-
        Returns a list of devices for an account at a given location (or all locations if using the default value 'all').

        Account IDs are provided by the CloudHome platform while Location IDs are defined by the account administrator.
    post:
      summary: newDevice
      tags:
        - devices
        - IOT
      responses: {}
      operationId: post-api-devices
    put:
      summary: updateDevice
      tags:
        - devices
        - IOT
      responses: {}
      operationId: put-api-devices
    delete:
      summary: removeDevice
      tags:
        - devices
        - IOT
      responses: {}
      operationId: delete-api-devices
    parameters:
      - schema:
          type: string
          example: jetsonsFutureHome
        name: accountid
        in: path
        required: true
        description: unique per account (see `'My Account'` for more information)
      - schema:
          type: string
          default: all
          example: seattle-office
        name: spaceid
        in: path
        description: location associated with the devices (see `'My Spaces'` for more information)
        required: true
components:
  schemas: {}
  securitySchemes:
    CloudHome Key:
      name: API Key
      type: apiKey
      in: header
      description: Provided upon account registration (see `'My Account'` for more information). API Keys can be used as Basic HTTP Authentication credentials and provide a substitute for the account's actual username and password. API Keys are only available to team accounts and there is only 1 key per account. API Keys do not support scopes and have therefore access to all contents of the account.
    HTTP Auth:
      type: http
      scheme: basic
      description: 'Basic HTTP Authentication as per [RFC-2617](https://tools.ietf.org/html/rfc2617) (Digest not supported). Note that Basic Auth with username and password as credentials is only available on accounts that have 2-factor-auth / 2-step-verification disabled. If you use 2fa, you should authenticate using OAuth2 instead.'
    OAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://cloudhome.io/oauth2/authorize'
          tokenUrl: 'https://cloudhome.io/oauth2/token'
          scopes:
            'devices:write': Read and modify your devices
            'locations:write': Read and modify your locations
            'accounts:write': Read and modify your accounts
            'users:write': Read and modify your users
            'devices:delete': Delete your devices
            'locations:delete': Delete your locations
            'users:delete': Delete your users
          refreshUrl: 'https://cloudhome.io/oauth2/refresh'
        implicit:
          authorizationUrl: 'https://cloudhome.io/oauth2/authorize'
          refreshUrl: 'https://cloudhome.io/oauth2/refresh'
          scopes:
            'devices:write': Read and modify your devices
            'locations:write': Read and modify your locations
            'accounts:write': Read and modify your accounts
            'users:write': Read and modify your users
            'devices:delete': Delete your devices
            'locations:delete': Delete your locations
            'users:delete': Delete your users
      description: 'OAuth 2 as per [RFC-6749](https://tools.ietf.org/html/rfc6749). OAuth2 is a protocol that lets external apps request authorization to private details in a user''s CloudHome account without getting their password. This is preferred over Basic Authentication because tokens can be limited to specific types of data, and can be revoked by users at any time.'
    OpenID Connect:
      type: openIdConnect
      openIdConnectUrl: 'https://cloudhome.io/auth/openid-configuration'
      description: ''
security:
  - CloudHome Key: []
